#!/bin/sh -u 
zenity --info --ok-label="Start" --width="500" --height="200" --title="Horopter Inc." --text "RFD is loaded. Click start to continue."
zenity --info --ok-label="OK" --width="500" --height="300" --title="Horopter Inc." --text "We have wondered from years, what lies in other dimensions... "
zenity --info --ok-label="OK" --width="500" --height="300" --title="Horopter Inc." --text "Until recently we didn't know the structure or\nlook of a wormhole.... "
zenity --info --ok-label="OK" --width="500" --height="300" --title="Horopter Inc." --text "Our enemy was hidden... \nIt was not 1D..\n not 2D... \nnot 3D... Ironically it was 2.3219D (what?)"
zenity --info --ok-label="OK" --width="500" --height="300" --title="Horopter Inc." --text "It was the fractal dimension,\n one which we are fascinated with since pythagorean age.\n We ignored it's value in daily life limiting it to graphics.\n It has come back to hunt us."
zenity --info --ok-label="OK" --width="500" --height="300" --title="Horopter Inc." --text "But we have our defender Manyu who will save us...."
zenity --info --ok-label="OK" --width="500" --height="300" --title="Horopter Inc." --text "Press e to exit fullscreen,\n q to quit any time,\n (left arrow) to move left,\n (right arrow) to move right\n and hit (spacebar) to shoot evil Kochus."
current=`pwd`
PATH=$PATH:$current
succession=$(zenity --entry --width="500" --height="300" --title="Koch Curve" --text "Enter the Villain [1-5]")
if [ $succession -le 5 ] && [ $succession -ge 0 ]
then
	color=$(zenity --entry --width="500" --height="300" --title="Koch Curve" --text "Enter the color of the Villain : \n1. RED \n2. GREEN \n3.BLUE  \n[1-3] \nOthers \n[4-9]")
		if [ $color -le 3 ] && [ $color -ge 1 ]
		then
			$(glc RFD.cpp)
			input=`echo "$succession $color"`
			res=0
			res=$(./graph.out "$input")
			zenity --info --ok-label="Okay" --width="500" --height="200" --title="Scorecard" --text "Your score is $res. Restart to play again."
		fi
	fi
fi
zenity --info --title="Horopter Inc." --ok-label="Finish" --width="500" --height="300" --text "Click finish to exit."
